/* Accredited MD programs with published applicant averages.
   Lives here rather than in the schools client component so server
   components, the PDF export and the gap check can all read it. */

export interface School {
  name: string;
  state: string;
  avgGpa: number;
  avgMcat: number;
  mission: string;
  inStatePref: "In-State Friendly" | "Out-of-State Friendly" | "Neutral";
}

export const SCHOOLS: School[] = [
  // ── Top Research ──────────────────────────────────────────────────────────
  { name: "Harvard Medical School",                          state: "MA", avgGpa: 3.90, avgMcat: 522, mission: "Research",                    inStatePref: "Neutral" },
  { name: "Johns Hopkins School of Medicine",               state: "MD", avgGpa: 3.90, avgMcat: 522, mission: "Research",                    inStatePref: "Neutral" },
  { name: "Stanford School of Medicine",                    state: "CA", avgGpa: 3.80, avgMcat: 520, mission: "Research",                    inStatePref: "Neutral" },
  { name: "Columbia Vagelos P&S",                           state: "NY", avgGpa: 3.85, avgMcat: 521, mission: "Research",                    inStatePref: "Neutral" },
  { name: "Perelman School of Medicine (Penn)",             state: "PA", avgGpa: 3.90, avgMcat: 521, mission: "Research",                    inStatePref: "Neutral" },
  { name: "Yale School of Medicine",                        state: "CT", avgGpa: 3.80, avgMcat: 520, mission: "Research",                    inStatePref: "Neutral" },
  { name: "Washington University School of Medicine",       state: "MO", avgGpa: 3.90, avgMcat: 522, mission: "Research",                    inStatePref: "Neutral" },
  { name: "Duke University School of Medicine",             state: "NC", avgGpa: 3.70, avgMcat: 519, mission: "Research",                    inStatePref: "Neutral" },
  { name: "University of Michigan Medical School",          state: "MI", avgGpa: 3.80, avgMcat: 517, mission: "Research",                    inStatePref: "In-State Friendly" },
  { name: "Northwestern Feinberg School of Medicine",       state: "IL", avgGpa: 3.90, avgMcat: 520, mission: "Research",                    inStatePref: "Neutral" },
  { name: "Vanderbilt University School of Medicine",       state: "TN", avgGpa: 3.80, avgMcat: 519, mission: "Research",                    inStatePref: "Neutral" },
  { name: "University of Chicago Pritzker",                 state: "IL", avgGpa: 3.90, avgMcat: 521, mission: "Research",                    inStatePref: "Neutral" },
  { name: "Weill Cornell Medicine",                         state: "NY", avgGpa: 3.80, avgMcat: 521, mission: "Research",                    inStatePref: "Neutral" },
  { name: "NYU Grossman School of Medicine",                state: "NY", avgGpa: 3.90, avgMcat: 522, mission: "Research",                    inStatePref: "Neutral" },
  { name: "Icahn School of Medicine at Mount Sinai",        state: "NY", avgGpa: 3.70, avgMcat: 519, mission: "Research",                    inStatePref: "Neutral" },
  { name: "University of Pittsburgh School of Medicine",    state: "PA", avgGpa: 3.70, avgMcat: 516, mission: "Research",                    inStatePref: "In-State Friendly" },
  { name: "Case Western Reserve School of Medicine",        state: "OH", avgGpa: 3.70, avgMcat: 516, mission: "Research",                    inStatePref: "Neutral" },
  { name: "UC San Diego School of Medicine",                state: "CA", avgGpa: 3.70, avgMcat: 517, mission: "Research",                    inStatePref: "In-State Friendly" },
  { name: "Emory University School of Medicine",            state: "GA", avgGpa: 3.70, avgMcat: 517, mission: "Research",                    inStatePref: "Neutral" },
  { name: "University of Texas Southwestern",               state: "TX", avgGpa: 3.80, avgMcat: 519, mission: "Research",                    inStatePref: "In-State Friendly" },
  { name: "Baylor College of Medicine",                     state: "TX", avgGpa: 3.80, avgMcat: 519, mission: "Research",                    inStatePref: "Neutral" },
  { name: "USC Keck School of Medicine",                    state: "CA", avgGpa: 3.70, avgMcat: 515, mission: "Research",                    inStatePref: "In-State Friendly" },
  { name: "Dartmouth Geisel School of Medicine",            state: "NH", avgGpa: 3.70, avgMcat: 515, mission: "Research",                    inStatePref: "Neutral" },
  { name: "Brown Warren Alpert Medical School",             state: "RI", avgGpa: 3.70, avgMcat: 515, mission: "Research",                    inStatePref: "Neutral" },
  { name: "University of Virginia School of Medicine",      state: "VA", avgGpa: 3.80, avgMcat: 517, mission: "Research",                    inStatePref: "In-State Friendly" },
  { name: "Ohio State University College of Medicine",      state: "OH", avgGpa: 3.70, avgMcat: 513, mission: "Research",                    inStatePref: "In-State Friendly" },
  { name: "University of Cincinnati College of Medicine",   state: "OH", avgGpa: 3.60, avgMcat: 511, mission: "Research",                    inStatePref: "In-State Friendly" },
  { name: "University of Maryland School of Medicine",      state: "MD", avgGpa: 3.70, avgMcat: 513, mission: "Research",                    inStatePref: "In-State Friendly" },
  { name: "Wake Forest University School of Medicine",      state: "NC", avgGpa: 3.60, avgMcat: 512, mission: "Research",                    inStatePref: "Neutral" },
  { name: "Medical University of South Carolina",           state: "SC", avgGpa: 3.60, avgMcat: 510, mission: "Research",                    inStatePref: "In-State Friendly" },
  { name: "Stony Brook University School of Medicine",      state: "NY", avgGpa: 3.60, avgMcat: 511, mission: "Research",                    inStatePref: "In-State Friendly" },
  { name: "Albany Medical College",                         state: "NY", avgGpa: 3.60, avgMcat: 511, mission: "Research",                    inStatePref: "Neutral" },
  { name: "Thomas Jefferson Sidney Kimmel SOM",             state: "PA", avgGpa: 3.60, avgMcat: 511, mission: "Research",                    inStatePref: "Neutral" },
  { name: "Medical College of Wisconsin",                   state: "WI", avgGpa: 3.70, avgMcat: 511, mission: "Research",                    inStatePref: "Neutral" },
  { name: "University of Florida College of Medicine",      state: "FL", avgGpa: 3.70, avgMcat: 513, mission: "Research",                    inStatePref: "In-State Friendly" },
  { name: "University of Miami Miller School of Medicine",  state: "FL", avgGpa: 3.70, avgMcat: 515, mission: "Research",                    inStatePref: "Neutral" },
  { name: "University of Central Florida COM",              state: "FL", avgGpa: 3.70, avgMcat: 511, mission: "Research",                    inStatePref: "In-State Friendly" },
  { name: "University of Houston College of Medicine",      state: "TX", avgGpa: 3.60, avgMcat: 508, mission: "Research",                    inStatePref: "In-State Friendly" },
  { name: "University of Texas Houston McGovern SOM",       state: "TX", avgGpa: 3.70, avgMcat: 513, mission: "Research",                    inStatePref: "In-State Friendly" },

  // ── Primary Care ──────────────────────────────────────────────────────────
  { name: "UCSF School of Medicine",                        state: "CA", avgGpa: 3.80, avgMcat: 517, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "Mayo Clinic Alix School of Medicine",            state: "MN", avgGpa: 3.90, avgMcat: 520, mission: "Primary Care",               inStatePref: "Neutral" },
  { name: "University of Washington School of Medicine",    state: "WA", avgGpa: 3.70, avgMcat: 512, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "UNC School of Medicine",                         state: "NC", avgGpa: 3.70, avgMcat: 513, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "UCLA David Geffen School of Medicine",           state: "CA", avgGpa: 3.80, avgMcat: 517, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "University of Vermont Larner COM",               state: "VT", avgGpa: 3.60, avgMcat: 511, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of Minnesota Medical School",         state: "MN", avgGpa: 3.70, avgMcat: 511, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "Oregon Health & Science University",             state: "OR", avgGpa: 3.60, avgMcat: 511, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "University of Colorado School of Medicine",      state: "CO", avgGpa: 3.70, avgMcat: 511, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of Iowa Carver College of Medicine",  state: "IA", avgGpa: 3.70, avgMcat: 511, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of Wisconsin School of Medicine",     state: "WI", avgGpa: 3.70, avgMcat: 511, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "Penn State College of Medicine",                 state: "PA", avgGpa: 3.60, avgMcat: 511, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of Nebraska Medical Center",          state: "NE", avgGpa: 3.70, avgMcat: 509, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of Kansas School of Medicine",        state: "KS", avgGpa: 3.60, avgMcat: 508, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of Oklahoma College of Medicine",     state: "OK", avgGpa: 3.60, avgMcat: 507, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of Kentucky College of Medicine",     state: "KY", avgGpa: 3.60, avgMcat: 507, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of Louisville School of Medicine",    state: "KY", avgGpa: 3.60, avgMcat: 508, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "Louisiana State University School of Medicine",  state: "LA", avgGpa: 3.60, avgMcat: 509, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of Utah School of Medicine",          state: "UT", avgGpa: 3.70, avgMcat: 510, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "Indiana University School of Medicine",          state: "IN", avgGpa: 3.70, avgMcat: 510, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of Alabama School of Medicine",       state: "AL", avgGpa: 3.60, avgMcat: 508, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of South Alabama COM",                state: "AL", avgGpa: 3.50, avgMcat: 507, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of South Dakota Sanford SOM",         state: "SD", avgGpa: 3.60, avgMcat: 502, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of Tennessee Health Science Center",  state: "TN", avgGpa: 3.60, avgMcat: 509, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of Missouri School of Medicine",      state: "MO", avgGpa: 3.60, avgMcat: 507, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of Missouri–Kansas City SOM",         state: "MO", avgGpa: 3.60, avgMcat: 505, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of Connecticut School of Medicine",   state: "CT", avgGpa: 3.60, avgMcat: 511, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "UMass Chan Medical School",                      state: "MA", avgGpa: 3.70, avgMcat: 514, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "SUNY Upstate Medical University",                state: "NY", avgGpa: 3.60, avgMcat: 509, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of Arizona COM – Tucson",             state: "AZ", avgGpa: 3.60, avgMcat: 508, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of Arizona COM – Phoenix",            state: "AZ", avgGpa: 3.60, avgMcat: 509, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "Creighton University School of Medicine",        state: "NE", avgGpa: 3.60, avgMcat: 509, mission: "Primary Care",               inStatePref: "Neutral" },
  { name: "Augusta University Medical College of Georgia",  state: "GA", avgGpa: 3.70, avgMcat: 509, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "Northeast Ohio Medical University",              state: "OH", avgGpa: 3.60, avgMcat: 507, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "Michigan State University College of Human Medicine", state: "MI", avgGpa: 3.50, avgMcat: 507, mission: "Primary Care",          inStatePref: "In-State Friendly" },
  { name: "Texas A&M College of Medicine",                  state: "TX", avgGpa: 3.60, avgMcat: 507, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "University of Texas Medical Branch (UTMB)",      state: "TX", avgGpa: 3.60, avgMcat: 507, mission: "Primary Care",               inStatePref: "In-State Friendly" },
  { name: "Uniformed Services University (USUHS)",          state: "MD", avgGpa: 3.60, avgMcat: 510, mission: "Primary Care",               inStatePref: "Neutral" },
  { name: "Tufts University School of Medicine",            state: "MA", avgGpa: 3.70, avgMcat: 514, mission: "Community Health",           inStatePref: "Neutral" },

  // ── Community Health & Underserved ────────────────────────────────────────
  { name: "Morehouse School of Medicine",                   state: "GA", avgGpa: 3.40, avgMcat: 505, mission: "Primary Care & Underserved",  inStatePref: "Neutral" },
  { name: "Howard University College of Medicine",          state: "DC", avgGpa: 3.40, avgMcat: 506, mission: "Primary Care & Underserved",  inStatePref: "Neutral" },
  { name: "Meharry Medical College",                        state: "TN", avgGpa: 3.40, avgMcat: 503, mission: "Primary Care & Underserved",  inStatePref: "Neutral" },
  { name: "Charles R. Drew University of Medicine",         state: "CA", avgGpa: 3.30, avgMcat: 500, mission: "Primary Care & Underserved",  inStatePref: "Neutral" },
  { name: "FIU Herbert Wertheim COM",                       state: "FL", avgGpa: 3.60, avgMcat: 508, mission: "Community Health",           inStatePref: "In-State Friendly" },
  { name: "University of Hawaii John A. Burns SOM",         state: "HI", avgGpa: 3.60, avgMcat: 508, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "East Carolina Brody School of Medicine",         state: "NC", avgGpa: 3.50, avgMcat: 506, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "Wayne State University School of Medicine",      state: "MI", avgGpa: 3.50, avgMcat: 508, mission: "Community Health",           inStatePref: "In-State Friendly" },
  { name: "University of Illinois College of Medicine",     state: "IL", avgGpa: 3.50, avgMcat: 510, mission: "Community Health",           inStatePref: "In-State Friendly" },
  { name: "Texas Tech TTUHSC School of Medicine",           state: "TX", avgGpa: 3.50, avgMcat: 506, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "Paul L. Foster SOM (TTUHSC El Paso)",            state: "TX", avgGpa: 3.40, avgMcat: 505, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "UT Health San Antonio Long SOM",                 state: "TX", avgGpa: 3.60, avgMcat: 508, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "University of Nevada Reno School of Medicine",   state: "NV", avgGpa: 3.50, avgMcat: 506, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "University of Mississippi School of Medicine",   state: "MS", avgGpa: 3.60, avgMcat: 507, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "University of North Dakota SOM",                 state: "ND", avgGpa: 3.60, avgMcat: 504, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "University of Arkansas for Medical Sciences",    state: "AR", avgGpa: 3.60, avgMcat: 506, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "University of South Carolina SOM",               state: "SC", avgGpa: 3.50, avgMcat: 507, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "University of New Mexico School of Medicine",    state: "NM", avgGpa: 3.60, avgMcat: 508, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "Eastern Virginia Medical School",                state: "VA", avgGpa: 3.60, avgMcat: 509, mission: "Primary Care & Underserved",  inStatePref: "Neutral" },
  { name: "Florida State University College of Medicine",   state: "FL", avgGpa: 3.60, avgMcat: 507, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "Florida Atlantic University COM",                state: "FL", avgGpa: 3.60, avgMcat: 507, mission: "Community Health",           inStatePref: "In-State Friendly" },
  { name: "Rutgers New Jersey Medical School",              state: "NJ", avgGpa: 3.60, avgMcat: 512, mission: "Community Health",           inStatePref: "In-State Friendly" },
  { name: "VCU School of Medicine",                         state: "VA", avgGpa: 3.60, avgMcat: 510, mission: "Community Health",           inStatePref: "In-State Friendly" },
  { name: "GWU School of Medicine and Health Sciences",     state: "DC", avgGpa: 3.60, avgMcat: 513, mission: "Community Health",           inStatePref: "Neutral" },
  { name: "Georgetown University School of Medicine",       state: "DC", avgGpa: 3.60, avgMcat: 514, mission: "Community Health",           inStatePref: "Neutral" },
  { name: "Tulane University School of Medicine",           state: "LA", avgGpa: 3.60, avgMcat: 511, mission: "Community Health",           inStatePref: "Neutral" },
  { name: "New York Medical College",                       state: "NY", avgGpa: 3.60, avgMcat: 511, mission: "Community Health",           inStatePref: "Neutral" },
  { name: "Boston University School of Medicine",           state: "MA", avgGpa: 3.60, avgMcat: 514, mission: "Community Health",           inStatePref: "Neutral" },
  { name: "Loyola Stritch School of Medicine",              state: "IL", avgGpa: 3.60, avgMcat: 511, mission: "Community Health",           inStatePref: "Neutral" },
  { name: "Rush Medical College",                           state: "IL", avgGpa: 3.60, avgMcat: 512, mission: "Community Health",           inStatePref: "Neutral" },
  { name: "Saint Louis University School of Medicine",      state: "MO", avgGpa: 3.70, avgMcat: 512, mission: "Community Health",           inStatePref: "Neutral" },
  { name: "Temple University Lewis Katz SOM",               state: "PA", avgGpa: 3.60, avgMcat: 511, mission: "Community Health",           inStatePref: "Neutral" },
  { name: "Drexel University College of Medicine",          state: "PA", avgGpa: 3.60, avgMcat: 511, mission: "Community Health",           inStatePref: "Neutral" },
  { name: "Universidad Central del Caribe SOM",             state: "PR", avgGpa: 3.40, avgMcat: 497, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "University of Puerto Rico School of Medicine",   state: "PR", avgGpa: 3.50, avgMcat: 500, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },
  { name: "Ponce Health Sciences University SOM",           state: "PR", avgGpa: 3.30, avgMcat: 494, mission: "Primary Care & Underserved",  inStatePref: "In-State Friendly" },

  // ── Osteopathic (DO) ──────────────────────────────────────────────────────
  { name: "Kirksville College of Osteopathic Medicine",     state: "MO", avgGpa: 3.50, avgMcat: 504, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Philadelphia College of Osteopathic Medicine",   state: "PA", avgGpa: 3.50, avgMcat: 505, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Michigan State University COM (DO)",             state: "MI", avgGpa: 3.50, avgMcat: 504, mission: "Osteopathic",                inStatePref: "In-State Friendly" },
  { name: "Ohio University Heritage College of Osteopathic Medicine", state: "OH", avgGpa: 3.50, avgMcat: 503, mission: "Osteopathic",      inStatePref: "In-State Friendly" },
  { name: "West Virginia School of Osteopathic Medicine",   state: "WV", avgGpa: 3.40, avgMcat: 500, mission: "Osteopathic",                inStatePref: "In-State Friendly" },
  { name: "Nova Southeastern University COM (DO)",          state: "FL", avgGpa: 3.40, avgMcat: 500, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "A.T. Still University – Arizona",                state: "AZ", avgGpa: 3.40, avgMcat: 501, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Touro University California (DO)",               state: "CA", avgGpa: 3.40, avgMcat: 501, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Lake Erie College of Osteopathic Medicine",      state: "PA", avgGpa: 3.40, avgMcat: 500, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Des Moines University COM (DO)",                 state: "IA", avgGpa: 3.50, avgMcat: 502, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Edward Via College of Osteopathic Medicine",     state: "VA", avgGpa: 3.40, avgMcat: 500, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Pacific Northwest University of Health Sciences", state: "WA", avgGpa: 3.40, avgMcat: 499, mission: "Osteopathic",              inStatePref: "Neutral" },
  { name: "Midwestern University – Chicago COM (DO)",       state: "IL", avgGpa: 3.50, avgMcat: 504, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Midwestern University – Arizona COM (DO)",       state: "AZ", avgGpa: 3.50, avgMcat: 504, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Rocky Vista University COM (DO)",                state: "CO", avgGpa: 3.50, avgMcat: 504, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Kansas City University COM (DO)",                state: "MO", avgGpa: 3.50, avgMcat: 504, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "NYIT College of Osteopathic Medicine",           state: "NY", avgGpa: 3.50, avgMcat: 503, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Rowan University SOM (DO)",                      state: "NJ", avgGpa: 3.50, avgMcat: 504, mission: "Osteopathic",                inStatePref: "In-State Friendly" },
  { name: "University of New England COM (DO)",             state: "ME", avgGpa: 3.40, avgMcat: 501, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Western University of Health Sciences COM (DO)", state: "CA", avgGpa: 3.50, avgMcat: 505, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Touro University Nevada (DO)",                   state: "NV", avgGpa: 3.40, avgMcat: 500, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Alabama College of Osteopathic Medicine",        state: "AL", avgGpa: 3.40, avgMcat: 499, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Arkansas College of Osteopathic Medicine",       state: "AR", avgGpa: 3.40, avgMcat: 499, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Sam Houston State University COM (DO)",          state: "TX", avgGpa: 3.40, avgMcat: 499, mission: "Osteopathic",                inStatePref: "In-State Friendly" },
  { name: "Marian University COM (DO)",                     state: "IN", avgGpa: 3.40, avgMcat: 500, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Idaho College of Osteopathic Medicine",          state: "ID", avgGpa: 3.40, avgMcat: 499, mission: "Osteopathic",                inStatePref: "In-State Friendly" },
  { name: "Lincoln Memorial Univ. – DeBusk COM (DO)",       state: "TN", avgGpa: 3.40, avgMcat: 500, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Burrell College of Osteopathic Medicine",        state: "NM", avgGpa: 3.40, avgMcat: 499, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Liberty University COM (DO)",                    state: "VA", avgGpa: 3.40, avgMcat: 500, mission: "Osteopathic",                inStatePref: "Neutral" },
  { name: "Campbell University COM (DO)",                   state: "NC", avgGpa: 3.50, avgMcat: 503, mission: "Osteopathic",                inStatePref: "Neutral" },

  // ── Caribbean ─────────────────────────────────────────────────────────────
  { name: "St. George's University SOM (Caribbean)",        state: "Intl", avgGpa: 3.30, avgMcat: 497, mission: "Caribbean",               inStatePref: "Out-of-State Friendly" },
  { name: "Ross University School of Medicine (Caribbean)", state: "Intl", avgGpa: 3.20, avgMcat: 495, mission: "Caribbean",               inStatePref: "Out-of-State Friendly" },
  { name: "Saba University School of Medicine (Caribbean)", state: "Intl", avgGpa: 3.20, avgMcat: 492, mission: "Caribbean",               inStatePref: "Out-of-State Friendly" },
  { name: "American University of the Caribbean SOM",       state: "Intl", avgGpa: 3.10, avgMcat: 490, mission: "Caribbean",               inStatePref: "Out-of-State Friendly" },
  { name: "St. Matthew's University School of Medicine",    state: "Intl", avgGpa: 3.10, avgMcat: 490, mission: "Caribbean",               inStatePref: "Out-of-State Friendly" },
];

export const ALL_STATES = [...new Set(SCHOOLS.map((s) => s.state))].sort();
