"use client";

import { Experience, ExperienceType } from "@/lib/types";

const TYPE_LABELS: Record<ExperienceType, string> = {
  shadowing: "Shadowing",
  volunteer: "Volunteer",
  clinical_work: "Clinical Work",
  research: "Research",
  other: "Other",
};

function formatDate(dateStr: string): string {
  const [year, month, day] = dateStr.split("-");
  const months = [
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
  ];
  return `${months[parseInt(month, 10) - 1]} ${parseInt(day, 10)}, ${year}`;
}

interface ExportButtonProps {
  experience: Experience;
}

export default function ExportButton({ experience }: ExportButtonProps) {
  const handleExport = async () => {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ unit: "pt", format: "letter" });

    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 60;
    const contentWidth = pageWidth - margin * 2;
    let y = 60;

    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("CliniLog — Clinical Experience Record", margin, y);
    y += 6;

    // Header underline
    doc.setDrawColor(99, 102, 241); // indigo-500
    doc.setLineWidth(1.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 24;

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(17, 24, 39); // gray-900
    doc.text(experience.title, margin, y);
    y += 18;

    // Type + Organization
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(99, 102, 241); // indigo-600
    doc.text(TYPE_LABELS[experience.type], margin, y);
    y += 14;

    doc.setTextColor(107, 114, 128); // gray-500
    doc.text(experience.organization, margin, y);
    y += 20;

    // Date range + hours
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(75, 85, 99); // gray-600
    const dateRange = `${formatDate(experience.start_date)} — ${
      experience.end_date ? formatDate(experience.end_date) : "Present"
    }`;
    doc.text(dateRange, margin, y);
    y += 14;

    const hoursDisplay =
      experience.hours % 1 === 0
        ? experience.hours.toString()
        : experience.hours.toFixed(1);
    doc.setFont("helvetica", "bold");
    doc.text(`${hoursDisplay} hours`, margin, y);
    y += 24;

    // Divider
    doc.setDrawColor(229, 231, 235); // gray-200
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 20;

    // Description section
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(55, 65, 81); // gray-700
    doc.text("DESCRIPTION", margin, y);
    y += 14;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(55, 65, 81);
    const descLines = doc.splitTextToSize(experience.description, contentWidth) as string[];
    doc.text(descLines, margin, y);
    y += descLines.length * 14 + 16;

    // Reflection section (if present)
    if (experience.reflection) {
      // Check if we need a new page
      if (y > doc.internal.pageSize.getHeight() - 100) {
        doc.addPage();
        y = 60;
      }

      doc.setDrawColor(229, 231, 235);
      doc.setLineWidth(0.5);
      doc.line(margin, y, pageWidth - margin, y);
      y += 20;

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(55, 65, 81);
      doc.text("REFLECTION", margin, y);
      y += 14;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(55, 65, 81);
      const reflLines = doc.splitTextToSize(experience.reflection, contentWidth) as string[];
      doc.text(reflLines, margin, y);
    }

    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175); // gray-400
    doc.text("Generated by CliniLog", margin, pageHeight - 30);

    doc.save(`${experience.title}.pdf`);
  };

  return (
    <button
      onClick={handleExport}
      className="inline-flex items-center gap-1.5 text-sm font-medium text-indigo-600 border border-indigo-200 bg-white hover:bg-indigo-50 px-3 py-1.5 rounded-lg transition-colors"
    >
      <svg
        className="w-4 h-4"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
        />
      </svg>
      Export PDF
    </button>
  );
}
