"use client";

import { Experience, ExperienceType } from "@/lib/types";

const TYPE_LABELS: Record<ExperienceType, string> = {
  shadowing: "Shadowing",
  volunteer: "Volunteer",
  clinical_work: "Clinical Work",
  research: "Research",
  other: "Other",
};

function formatDate(dateStr: string): string {
  const [year, month, day] = dateStr.split("-");
  const months = [
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
  ];
  return `${months[parseInt(month, 10) - 1]} ${parseInt(day, 10)}, ${year}`;
}

interface ExportAllButtonProps {
  experiences: Experience[];
}

export default function ExportAllButton({ experiences }: ExportAllButtonProps) {
  if (experiences.length === 0) return null;

  const handleExport = async () => {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ unit: "pt", format: "letter" });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 60;
    const contentWidth = pageWidth - margin * 2;

    const totalHours = experiences.reduce((sum, e) => sum + e.hours, 0);
    const totalHoursDisplay =
      totalHours % 1 === 0 ? totalHours.toString() : totalHours.toFixed(1);

    // ── Cover page ──────────────────────────────────────────────────────────
    let y = 200;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(17, 24, 39);
    doc.text("CliniLog", pageWidth / 2, y, { align: "center" });
    y += 30;

    doc.setFontSize(15);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(99, 102, 241);
    doc.text("Clinical Experience Summary", pageWidth / 2, y, { align: "center" });
    y += 50;

    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.5);
    doc.line(margin + 60, y, pageWidth - margin - 60, y);
    y += 40;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(75, 85, 99);
    doc.text(`Total Experiences: ${experiences.length}`, pageWidth / 2, y, {
      align: "center",
    });
    y += 22;
    doc.text(`Total Hours: ${totalHoursDisplay} hrs`, pageWidth / 2, y, {
      align: "center",
    });

    // Cover page footer
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text("Generated by CliniLog", margin, pageHeight - 30);

    // ── One page per experience ──────────────────────────────────────────────
    for (const experience of experiences) {
      doc.addPage();
      y = 60;

      // Section header
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.setTextColor(17, 24, 39);
      doc.text(experience.title, margin, y);
      y += 6;

      doc.setDrawColor(99, 102, 241);
      doc.setLineWidth(1.5);
      doc.line(margin, y, pageWidth - margin, y);
      y += 18;

      // Type + Organization
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(99, 102, 241);
      doc.text(TYPE_LABELS[experience.type], margin, y);
      y += 14;

      doc.setTextColor(107, 114, 128);
      doc.text(experience.organization, margin, y);
      y += 18;

      // Date range + hours
      doc.setFontSize(10);
      doc.setTextColor(75, 85, 99);
      const dateRange = `${formatDate(experience.start_date)} — ${
        experience.end_date ? formatDate(experience.end_date) : "Present"
      }`;
      doc.text(dateRange, margin, y);
      y += 14;

      const hoursDisplay =
        experience.hours % 1 === 0
          ? experience.hours.toString()
          : experience.hours.toFixed(1);
      doc.setFont("helvetica", "bold");
      doc.text(`${hoursDisplay} hours`, margin, y);
      y += 22;

      // Divider
      doc.setDrawColor(229, 231, 235);
      doc.setLineWidth(0.5);
      doc.line(margin, y, pageWidth - margin, y);
      y += 18;

      // Description
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(55, 65, 81);
      doc.text("DESCRIPTION", margin, y);
      y += 14;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(55, 65, 81);
      const descLines = doc.splitTextToSize(experience.description, contentWidth) as string[];
      doc.text(descLines, margin, y);
      y += descLines.length * 14 + 14;

      // Reflection (if present)
      if (experience.reflection) {
        doc.setDrawColor(229, 231, 235);
        doc.setLineWidth(0.5);
        doc.line(margin, y, pageWidth - margin, y);
        y += 18;

        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        doc.setTextColor(55, 65, 81);
        doc.text("REFLECTION", margin, y);
        y += 14;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(55, 65, 81);
        const reflLines = doc.splitTextToSize(experience.reflection, contentWidth) as string[];
        doc.text(reflLines, margin, y);
      }

      // Footer on each page
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(156, 163, 175);
      doc.text("Generated by CliniLog", margin, pageHeight - 30);
    }

    doc.save("clinilog-experiences.pdf");
  };

  return (
    <button
      onClick={handleExport}
      className="inline-flex items-center gap-2 text-sm font-medium text-gray-600 border border-gray-200 bg-white hover:bg-gray-50 px-4 py-2.5 rounded-xl transition-colors focus:outline-none focus:ring-2 focus:ring-gray-300 focus:ring-offset-2 whitespace-nowrap"
    >
      <svg
        className="w-4 h-4"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M12 10v6m0 0l-3-3m3 3l3-3M3 17V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z"
        />
      </svg>
      Export All to PDF
    </button>
  );
}
