"use client";

import { School } from "@/lib/schools";

/**
 * Clean PDF of every school marked Applying, for sharing with an advisor.
 * jsPDF is imported on click so it never lands in the initial page bundle.
 */
export default function ExportTargetList({
  schools,
  userName,
}: {
  schools: School[];
  userName: string;
}) {
  async function exportPdf() {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ unit: "pt", format: "letter" });
    const M = 56;
    let y = M;

    const today = new Date();
    const MONTHS = ["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"];
    const stamp = `${String(today.getDate()).padStart(2, "0")} ${MONTHS[today.getMonth()]} ${today.getFullYear()}`;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("Target School List", M, y);
    y += 18;

    doc.setFont("courier", "normal");
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(`${userName} / ${stamp} / ${schools.length} SCHOOLS`, M, y);
    doc.setTextColor(0);
    y += 16;

    doc.setDrawColor(190);
    doc.line(M, y, 612 - M, y);
    y += 22;

    // Column headings
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.text("SCHOOL", M, y);
    doc.text("ST", 388, y);
    doc.text("AVG GPA", 424, y);
    doc.text("AVG MCAT", 492, y);
    y += 6;
    doc.setDrawColor(220);
    doc.line(M, y, 612 - M, y);
    y += 14;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);

    for (const s of schools) {
      if (y > 720) {
        doc.addPage();
        y = M;
      }
      const name = s.name.length > 52 ? `${s.name.slice(0, 51)}…` : s.name;
      doc.text(name, M, y);
      doc.setFont("courier", "normal");
      doc.setFontSize(9);
      doc.text(s.state, 388, y);
      doc.text(s.avgGpa.toFixed(2), 424, y);
      doc.text(String(s.avgMcat), 492, y);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      y += 8;
      doc.setDrawColor(235);
      doc.line(M, y, 612 - M, y);
      y += 14;
    }

    doc.setFont("courier", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by ClinicLog MD", M, 756);

    doc.save("target-school-list.pdf");
  }

  if (schools.length === 0) return null;

  return (
    <button
      onClick={exportPdf}
      className="btn-ghost text-xs font-semibold"
      style={{ padding: "8px var(--sp-2)" }}
    >
      Export target list ({schools.length})
    </button>
  );
}
